apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocoa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocoa
    app.kubernetes.io/part-of: byoc-app-tbmy
  name: ocoa2qan
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: ocoa
    weight: null
status: {}
